version: '3'
services:
  api:
    build: .
    command: python api_project/manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    networks: 
      main:
        aliases: 
          - api
  front:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile

    ports: 
      - 4201:4201
    tty: true
    depends_on: 
      - api
    links: 
      - api:api
    networks: 
      main:
        aliases: 
          - nginx
networks: 
  main:
